server:
  port: 9000

spring:
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/GreenERP
    username: ${mysql.greenerp.username}
    password: ${mysql.greenerp.password}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/green-erp

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG