= GreenERP API Documentation
Diego Reidel
:operation-curl-request-title: Example request
:operation-httpie-request-title: Example request
:operation-http-response-title: Example response
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[resources]]
= Resources

[[resources_contractors]]
== Contractors

The Contractors resource is used to list and create contractors

=== Listing contractors

A `GET` request will list all the contractors.

operation::listing-contractors[snippets='http-request,request-headers,response-fields,http-response']

=== Creating a contractor
A `POST` request is used to create a contractor.

operation::creating-a-contractor[snippets='http-request,request-headers,request-fields,http-response']

[[resources_contractor]]
== Contractor
The Contractor resource is used to retrieve and update a specific contractor.

=== Retrieving a contractor
A `GET` request will retrieve a specific contractor.

operation::detailing-contractor[snippets='http-request,request-headers,path-parameters,response-fields,http-response']

=== Updating a contractor
A `PATCH` request will update the data for a specific contractor.

operation::updating-a-contractor[snippets='http-request,request-headers,path-parameters,response-fields,http-response']



[[resources_rates]]
== Rates

The Rates resource is used to list and create contractor rates

=== Listing contractor rates

A `GET` request will list all the rates associated with a contractor.

operation::listing-contractor-rates[snippets='http-request,request-headers,path-parameters,response-fields,http-response']

=== Creating a contractor rate
A `POST` request is used to create a contractor rate.

operation::creating-a-rate[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[resources_rate]]
== Rate
The Rate resource is used to retrieve, update, and delete a specific contractor's rate.

=== Retrieving a contractor rate
A `GET` request will retrieve a specific contractor's rate.

operation::detailing-a-rate[snippets='http-request,request-headers,path-parameters,http-response']


=== Updating a contractor rate
A `PATCH` request will update the data for a specific contractor's rate.

operation::updating-a-rate[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== Deleting a contractor rate
A `DELETE` request will delete a specific contractor's rate.

operation::deleting-a-rate[snippets='http-request,request-headers,path-parameters,http-response']
