name: CI - Build, Test & Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Load .env file
        run: |
          set -a
          source .env
          set +a

      - name: Build, run tests, and generate REST Docs
        run: ./mvnw clean verify

      - name: Upload test report (only if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload REST Docs (only on main branch)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DIEGO_TOKEN }}
          publish_dir: ./target/generated-docs
