name: CI - Build, Test & Docs

env:
  MYSQL_GREENERP_HOST: localhost
  MYSQL_GREENERP_PORT: 3306
  MYSQL_GREENERP_USERNAME: not-a-real-username
  MYSQL_GREENERP_PASSWORD: not-a-real-password
  MYSQL_ROOT_PASSWORD: not-a-real-password
  MYSQL_GREENERP_DATABASE: not-real
  MYSQL_KEYCLOAK_DATABASE: not-real
  MYSQL_KEYCLOAK_USERNAME: not-a-real-username
  MYSQL_KEYCLOAK_PASSWORD: not-a-real-password
  RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/green-erp
  KEYCLOAK_ADMIN: not-a-real-username
  KEYCLOAK_PASSWORD: not-a-real-password
  RABBITMQ_HOST: localhost
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, run tests, and generate REST Docs
        run: ./mvnw clean verify

      - name: Upload test report (only if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload REST Docs (only on main branch)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DIEGO_TOKEN }}
          publish_dir: ./target/generated-docs
